# клас-драйвер для MySQL
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver

# Адреса вашого сервера MySQL (localhost — ваш ПК, 3306 — стандартний порт, autobase_db — назва схеми)
hibernate.connection.url=jdbc:mysql://localhost:3306/autobase_db?createDatabaseIfNotExist=true&serverTimezone=UTC

# Логін та пароль до вашого локального сервера MySQL
hibernate.connection.username=root
hibernate.connection.password=1234

# Діалект мови SQL, адаптований під MySQL 8
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Відображення запитів у консолі (залишаємо як було)
hibernate.show_sql=true
hibernate.format_sql=true

# Зміна режиму роботи з таблицями
hibernate.hbm2ddl.auto=update